<?php
/**
 * @package Apache Solr indexing for searching
 * @copyright Umang Gupta
 * @author Umang
 * @method create
 * @method update
 * @method delete
 * @method index
 */
define('HOST', '127.0.0.1');
define('PORT','8983');
define('CORE0','core0');
define('DRUPAL_ROOT', getcwd());
//include_once DRUPAL_ROOT .'/Apache/Solr/Service.php';
require_once( DRUPAL_ROOT.'/Apache/Solr/Service.php' );
/**
 * Implement hook_menu()
 */
function apache_solr_menu() {
	$item = array();
	$item['solr/index'] = array(
			'title'=>t('Solr Index'),
			'description'=>t('Solr indexing'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('index'),
			'access arguments'=>array('access administration pages')
	);
	return $item;
}

function index($form,&$form_state) {
	$form = array();
	$form['index_option'] = array(
			'#type'=>'select',
			'#required'=> TRUE,
			'#options'=>array('create'=>'Create','update'=>'Update','delete'=>'Delete'),
	);
	$form['create_submit'] = array(
			'#type'=>'submit',
			'#value'=>'create',
	);
	return $form;
}
function index_submit($form,&$form_state) {
	$value = $form_state['values']['index_option'];
	if($value == "create") {
		create();
	}
	if($value == "update") {
		update();
	}
}
function create(){
	$options = array
	(
			'hostname' => HOST,
			'port'     => PORT,
			'path'	   =>'/solr/core1'	
	);
	
	$client = new SolrClient($options);
	
	$doc = new SolrInputDocument();
	
	$doc->addField('id', uniqid());
	$doc->addField('fname', 'shilkiya');
	
	$updateResponse = $client->addDocument($doc);
	
	// you will have to commit changes to be written if you didn't use $commitWithin
	$client->commit();
	
	print_r($updateResponse->getResponse());
	
	
	/* $solr = new Apache_Solr_Service(HOST,PORT,'/solr/core0');
	//print_r($solr);exit();
	if(!$solr->ping()){
		drupal_set_message('Server not connected');
	}
	else{
		drupal_set_message('Server connected');
	}
	$documents = array();
	$document = new Apache_Solr_Document();
	$document->fname = "Umang";
	$solr->addDocument($document);
	$solr->commit(true); */
	//$solr->optimize();
	//try{
	//$query = db_query("select * from {user_data}");
	//print_r($query);exit();
	/*foreach ($query as $result){
		$document->id = uniqid();
		$document->fname = $result->first_name;
		//$document->lname = $result->last_name;
		$document->email = $result->email;
		$document->city  = $result->city;
		//$document->company=$result->company_name;
		//$document->country=$result->country;
		//$document->state = $result->state;
		$document->zip   = $result->zip;
		//$document->text  = $result->address;
		//$document->text  = $result->phone1;
		//$document->text  = $result->phone2;
		//print_r($document);exit();
		 //print_r($solr);exit();
		$solr->addDocument($document);
		$solr->commit();
		$solr->optimize();
		exit();
		//$documents[] = $document;
	}//exit();
		//print_r($documents);exit();
	//$solr->addDocuments($documents);
	//$solr->commit();
	//$solr->optimize();
	drupal_set_message("Create Index successfully");
	}
	catch (Exception $e) {
		drupal_set_message($e->getMessage(),'error');
	}*/
}

function update(){
	drupal_set_message("Update Index successfully");
}
